browser:
  browserName: CHROME
  headlessBrowser: false
  webElementTimeOut: 15

environment:
  test:
    envName: test
    appURL: http://146.59.32.4/index.php
    basketUrl: http://146.59.32.4/index.php?controller=cart&action=show
    active: true
    howManyProductsAddToBasket: 5
    customizableMugText: Bankai Zanka No Tachi
